use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum Action {
    Confirm,
    Cycle,
    Delete,
    EnterCmdMode,
    EnterDisplaySelectMode,
    EnterHelpMode,
    EnterObserveMode,
    EnterSessionLoadMode,
    EnterSessionSaveMode,
    Escape,
    Execute,
    IntervalDecrease,
    IntervalIncrease,
    KillPane,
    LoadLatestSession,
    MoveDown,
    MoveLeft,
    MoveRight,
    MoveUp,
    PaneDecreaseHorizontal,
    PaneDecreaseVertical,
    PaneIncreaseHorizontal,
    PaneIncreaseVertical,
    Pause,
    Quit,
    Rename,
    Resume,
    SaveSession,
    Search,
    ScrollTop,
    ScrollBottom,
    SplitHorizontal,
    SplitVertical,
    TabComplete,
    WrapToggle,
    ZenToggle,
}
